### ISSUE TITLE
Cluster Creation - Permissions issues

### ISSUE THREAD

**Issue by leestott** [research-software-reactor/cyclecloud#23]
To Create a resource from Cycle cloud head node  VM needs read access on the Azure Subscription to read Azure MarketPlace Agreement. 

During the Azure Marketplace deployment process a check box is required to be selected to agree to the terms and conditions of the license. (Without Read access to the subscription) the license agreement cannot be viewed.

**Comment by leestott** [comment]
The Cycle Cloud Head Node needs at least Reader Permission over the Azure Subscription

Add the Cycle Cloud VM Head Node to Subscription permissions as reader 

Example of error received

```
Traceback (most recent call last):   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/plugins/cloud/cluster/phases/stage_resources.py", line 162, in handle     info = nodes.get_jetpack_info(node, cache)   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/plugins/cloud/nodes.py", line 130, in get_jetpack_info     os = Images.getImageData(node, provider.get_image_data_provider()).getOSType()   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/azurelib/live_handler.py", line 97, in getAgreementTerms     return self.provider.get_agreement_terms(platform_image_id.publisher, platform_image_id.offer, platform_image_id.sku)   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/azurelib/live_handler.py", line 1067, in get_agreement_terms     _status, agreement_terms = MarketplaceAgreements.get(self.client, 'virtualmachine', publisher, offer, sku)   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/azurelib/live_handler.py", line 1067, in get_agreement_terms     _status, agreement_terms = MarketplaceAgreements.get(self.client, 'virtualmachine', publisher, offer, sku)   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/baiji-lib.zip/baiji/army/rest/marketplace/MarketplaceAgreements.py", line 104, in get   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/baiji-lib.zip/baiji/army/client.py", line 437, in request   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/baiji-lib.zip/baiji/army/client.py", line 196, in func_retry   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/baiji-lib.zip/baiji/army/client.py", line 432, in make_request   File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-*********-****-*********-************/lib/python/baiji-lib.zip/baiji/army/client.py", line 345, in raise_or_return baiji.exception.BaijiAuthenticationError: AuthorizationFailed - The client '*********-****-*********-************' with object id '*********-****-*********-************' does not have authorization to perform action 'Microsoft.MarketplaceOrdering/offerTypes/publishers/offers/plans/agreements/read' over scope '/subscriptions/*********-****-*********-************'.
```
-----

The Key issue is Permissions

```
 The client '*********-****-*********-************' with object id '*********-****-*********-************' does not have authorization to perform action 'Microsoft.MarketplaceOrdering/offerTypes/publishers/offers/plans/agreements/read' over scope '/subscriptions/*********-****-*********-************'.
```



![AzurePermission](https://user-images.githubusercontent.com/2511341/58164520-e4a0a400-7c7d-11e9-8218-12816171be49.JPG)

After permissions are added you may need to stop and start the VM to have the permissions active

**Comment by leestott** [comment]
This issue has been resolved with the creation of this script which automates the installation process for non Subscription owners and added the Cycle Cloud Head node to contributer permissions of the subscription simply run the following installation script. 
https://github.com/research-software-reactor/cyclecloud/tree/master/arm-templates
